# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: blesta-test

services:
  proxy:
    image: traefik:3
    command:
      - --accessLog=true
      - --entryPoints.http.address=:8080/tcp
      - --entryPoints.https.address=:8443/tcp
      - --providers.file.filename=/etc/traefik/dynamic.yaml
    ports:
      - 4200:8080/tcp
      - 4201:8443/tcp
    configs:
      - source: traefik-config
        target: /etc/traefik/dynamic.yaml

  blesta:
    image: ${BLESTA_IMAGE:-localhost/blesta:latest}
    platform: ${BLESTA_PLATFORM:-}
    develop:
      watch:
        - path: Dockerfile
          action: rebuild
        - path: docker/
          action: rebuild
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      BLESTA_ADDRESS: 127.0.0.1
      BLESTA_CRON_SCHEDULE: "#"
      BLESTA_HOST: localhost
    tmpfs:
      - /run:uid=65532,gid=65532,mode=0755,exec,nodev,nosuid
      - /tmp:uid=65532,gid=65532,mode=2777,noexec,nodev,nosuid
    depends_on:
      - mariadb
      - mailpit

  mariadb:
    image: docker.io/library/mariadb:11
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    environment:
      MARIADB_DATABASE: blesta
      MARIADB_USER: blesta
      MARIADB_PASSWORD: blesta
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 4202:3306/tcp
    tmpfs:
      - /var/lib/mysql
    configs:
      - source: mariadb-config
        target: /etc/mysql/conf.d/blesta.cnf

  mailpit:
    image: axllent/mailpit:latest
    environment:
      MP_POP3_AUTH: blesta:blesta
    networks:
      default:
        aliases:
          - mailpit
          - mailpit.local
    ports:
      - 4203:8025/tcp

configs:
  traefik-config:
    content: |
      http:
        routers:
          blesta-http:
            rule: HostRegexp(`.+`)
            service: blesta
            entryPoints: [http]
          blesta-https:
            rule: HostRegexp(`.+`)
            service: blesta
            entryPoints: [https]
            tls: {}
        services:
          blesta:
            loadBalancer:
              servers:
                - url: http://blesta:8080

  mariadb-config:
    content: |
      [mysqld]
      max_allowed_packet=128M
      wait_timeout=3600
